### 회원 생성 실패 (특수문자 미포함)
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "junghwan",
  "password": "qwer1234"
}

### 회원 생성 실패 (길이 제한)
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "password": "qwer1234@"
}

### 회원 생성 성공
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "junghwan",
  "password": "qwer1234@"
}

### 로그인 실패
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin123@

### 로그인 성공 (관리자)
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin1234@

### 로그인 성공 (사용자)
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=junghwan&password=qwer1234@

### 내 정보 확인
GET http://localhost:8080/members/me

### 로그아웃
POST http://localhost:8080/logout

### 전체 콘텐츠 조회
GET http://localhost:8080/contents?page=1&size=5

### 상세 콘텐츠 조회
GET http://localhost:8080/contents/11

### 콘텐츠 생성
POST http://localhost:8080/contents
Content-Type: application/json

{
  "title": "실패는 학습의 출발점이다",
  "description": "Failure is the starting point of learning. - 무정 영스턴 -"
}

### 콘텐츠 수정
PUT http://localhost:8080/contents/1
Content-Type: application/json

{
  "title": "수정된 제목",
  "description": "수정된 내용"
}

### 인기 조회순 콘텐츠 보기
GET http://localhost:8080/contents/popular

### 검색 콘텐츠 보기 ({사용자명})
GET http://localhost:8080/members/admin/contents

### 콘텐츠 삭제
DELETE http://localhost:8080/contents/1


